version: '3.4'
services:

  db:
    image: mysql:5.6
    container_name: client-db
    tty: true
    restart: unless-stopped
    volumes:
    - dbdata:/var/lib/mysql
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-billing_client}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-pass}
    networks:
      - client-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-app
    tty: true
    restart: unless-stopped
    ports:
      - ${DOCKER_CONTAINER_PORT:-80}:80
    volumes:
      - ./:/var/www/html/
    networks:
      - client-network

networks:
  client-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
